### ISSUE TITLE
[update]Remove and add some attributes

### ISSUE THREAD

**Issue by a-little-dust** [SoftwareEngineeringMedical/Tangxiaozhi-Database#7]
- [x] 1.去掉原有的heart_rate，新建一个，主码是patient_id和record_time，加一个int 类型的heart_rate属性
- [x] 2. 砍掉日程表这个功能，去掉schedule这个视图
- [x] 3. 在exercise表里面加入：
  - Int类型 calorie
  - Int pace（配速，例如1分40秒/km就把110存进数据库）（放在派生表）
  - decimal(5,2) distance（放在派生表）
- [x] 4. 修改scenario表，只保留下面的内容：
patient_id, category, duration
然后再添加字段：
Int类型 calorie 表示这个运动方案对应的卡路里

- [ ] #10

**Comment by VictorHuu** [comment]
Reference:
| Physical Activity                                       | MET     |
|---------------------------------------------------------|---------|
| **Moderate-intensity activities**                        |         |
| walking, 3.0 mph (4.8 km/h)                               | 3.0[12] |
| sweeping or mopping floors, vacuuming carpets            | 3 to 3.5[12] |
| yoga session with asanas and pranayama                   | 3.3[13] |
| **Vigorous intensity activities**                        |         |
| aerobic dancing, medium effort                            | 6.0[14] |
| jumping jacks                                            | >6.0[16] |
| sun salutation (Surya Namaskar, vigorous with transition jumps) | 7.4[13] |
| jogging, 5.6 mph (9.0 km/h)                              | 8.8[14] |
| rope jumping (66/min)                                    | 9.8[14] |
| rope jumping (84/min)                                    | 10.5[14] |
| rope jumping (100/min)                                   | 11.0[14] |
| jogging, 6.8 mph (10.9 km/h)                             | 11.2[14] |
